"""
Central registry describing every algorithm JCRYPT supports.

This is the single source of truth for:
  - the dropdown/card selector on the homepage
  - the dynamic parameter fields shown per algorithm
  - the /algorithms reference page
  - the homepage statistics (counts are derived, never hardcoded)
"""

SYMMETRIC_ENCRYPTION = [
    {
        "id": "aes-128-gcm",
        "name": "AES-128-GCM",
        "category": "Symmetric Encryption",
        "type": "Authenticated Block Cipher (AEAD)",
        "operations": ["Encrypt", "Decrypt"],
        "key": "128-bit key (Base64), required",
        "params": ["key"],
        "security": "Recommended",
        "description": (
            "AES-GCM combines AES in counter mode with a Galois MAC, providing "
            "both confidentiality and integrity in one pass."
        ),
        "usage": "General-purpose secure encryption for sensitive data at rest or in transit.",
    },
    {
        "id": "aes-192-gcm",
        "name": "AES-192-GCM",
        "category": "Symmetric Encryption",
        "type": "Authenticated Block Cipher (AEAD)",
        "operations": ["Encrypt", "Decrypt"],
        "key": "192-bit key (Base64), required",
        "params": ["key"],
        "security": "Recommended",
        "description": "AES-GCM with a 192-bit key, offering a higher security margin than AES-128.",
        "usage": "Used where policy requires a larger AES key size than 128 bits.",
    },
    {
        "id": "aes-256-gcm",
        "name": "AES-256-GCM",
        "category": "Symmetric Encryption",
        "type": "Authenticated Block Cipher (AEAD)",
        "operations": ["Encrypt", "Decrypt"],
        "key": "256-bit key (Base64), required",
        "params": ["key"],
        "security": "Recommended",
        "description": "AES-GCM with a 256-bit key, the strongest AES variant offered here.",
        "usage": "Preferred for long-term confidentiality of highly sensitive data.",
    },
    {
        "id": "chacha20-poly1305",
        "name": "ChaCha20-Poly1305",
        "category": "Symmetric Encryption",
        "type": "Authenticated Stream Cipher (AEAD)",
        "operations": ["Encrypt", "Decrypt"],
        "key": "256-bit key (Base64), required",
        "params": ["key"],
        "security": "Recommended",
        "description": (
            "A stream cipher paired with the Poly1305 MAC. Fast in software and "
            "widely used in TLS and modern protocols as an AES alternative."
        ),
        "usage": "Good choice on platforms without hardware AES acceleration.",
    },
    {
        "id": "fernet",
        "name": "Fernet",
        "category": "Symmetric Encryption",
        "type": "Authenticated Encryption (AES-128-CBC + HMAC-SHA256)",
        "operations": ["Encrypt", "Decrypt"],
        "key": "Fernet key (URL-safe Base64), required",
        "params": ["key"],
        "security": "Recommended",
        "description": (
            "A high-level recipe that bundles AES-128-CBC with HMAC-SHA256 "
            "authentication into one URL-safe token format."
        ),
        "usage": "Simple, hard-to-misuse encryption for application-level secrets and tokens.",
    },
]

CLASSICAL_CIPHERS = [
    {
        "id": "caesar",
        "name": "Caesar Cipher",
        "category": "Classical Ciphers",
        "type": "Substitution Cipher",
        "operations": ["Encrypt", "Decrypt"],
        "key": "Integer shift value",
        "params": ["shift"],
        "security": "Educational only — not secure",
        "description": "Shifts each letter by a fixed number of positions in the alphabet.",
        "usage": "Teaching the basic idea of substitution ciphers; not for real security.",
    },
    {
        "id": "rot13",
        "name": "ROT13",
        "category": "Classical Ciphers",
        "type": "Substitution Cipher",
        "operations": ["Encode", "Decode"],
        "key": "None",
        "params": [],
        "security": "Educational only — not secure",
        "description": "A special case of the Caesar cipher with a fixed shift of 13.",
        "usage": "Historically used to obscure spoiler text or puzzle answers, not for security.",
    },
    {
        "id": "atbash",
        "name": "Atbash Cipher",
        "category": "Classical Ciphers",
        "type": "Substitution Cipher",
        "operations": ["Encrypt", "Decrypt"],
        "key": "None",
        "params": [],
        "security": "Educational only — not secure",
        "description": "Reverses the alphabet: A maps to Z, B maps to Y, and so on.",
        "usage": "One of the oldest known ciphers; used today only for teaching.",
    },
    {
        "id": "vigenere",
        "name": "Vigenere Cipher",
        "category": "Classical Ciphers",
        "type": "Polyalphabetic Substitution Cipher",
        "operations": ["Encrypt", "Decrypt"],
        "key": "Text keyword",
        "params": ["key"],
        "security": "Educational only — not secure",
        "description": "Uses a repeating keyword to select a different Caesar shift for each letter.",
        "usage": "Illustrates polyalphabetic substitution; broken by frequency analysis techniques.",
    },
    {
        "id": "affine",
        "name": "Affine Cipher",
        "category": "Classical Ciphers",
        "type": "Mathematical Substitution Cipher",
        "operations": ["Encrypt", "Decrypt"],
        "key": "Integers a and b",
        "params": ["a", "b"],
        "security": "Educational only — not secure",
        "description": "Applies the function (a*x + b) mod 26 to each letter's position.",
        "usage": "Demonstrates modular arithmetic in cryptography; trivially breakable.",
    },
]

HASH_ALGORITHMS = [
    {
        "id": "md5",
        "name": "MD5",
        "category": "Hashing",
        "type": "Cryptographic Hash",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Broken",
        "description": "Produces a 128-bit digest. Practical collisions have been demonstrated.",
        "usage": "Legacy checksums only — never for passwords, signatures, or integrity of sensitive data.",
    },
    {
        "id": "sha1",
        "name": "SHA-1",
        "category": "Hashing",
        "type": "Cryptographic Hash",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Deprecated",
        "description": "Produces a 160-bit digest. Collision attacks make it unsuitable for security use.",
        "usage": "Avoid for new systems; retained here for compatibility and education.",
    },
    {
        "id": "sha224",
        "name": "SHA-224",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-2 family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "A truncated 224-bit variant of SHA-256.",
        "usage": "General-purpose hashing where a smaller digest is preferred.",
    },
    {
        "id": "sha256",
        "name": "SHA-256",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-2 family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "The most widely deployed member of the SHA-2 family.",
        "usage": "File integrity checks, digital signatures, certificate fingerprints.",
    },
    {
        "id": "sha384",
        "name": "SHA-384",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-2 family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "A truncated 384-bit variant of SHA-512.",
        "usage": "Used where a larger digest than SHA-256 is desired.",
    },
    {
        "id": "sha512",
        "name": "SHA-512",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-2 family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "Produces a 512-bit digest with a large security margin.",
        "usage": "High-assurance integrity checks and cryptographic protocols.",
    },
    {
        "id": "sha3_224",
        "name": "SHA-3-224",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-3 / Keccak family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "Based on the Keccak sponge construction, structurally distinct from SHA-2.",
        "usage": "An alternative to SHA-2 for applications wanting design diversity.",
    },
    {
        "id": "sha3_256",
        "name": "SHA-3-256",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-3 / Keccak family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "Based on the Keccak sponge construction, structurally distinct from SHA-2.",
        "usage": "General-purpose hashing with strong security proofs.",
    },
    {
        "id": "sha3_384",
        "name": "SHA-3-384",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-3 / Keccak family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "Based on the Keccak sponge construction, structurally distinct from SHA-2.",
        "usage": "Used where a larger SHA-3 digest is desired.",
    },
    {
        "id": "sha3_512",
        "name": "SHA-3-512",
        "category": "Hashing",
        "type": "Cryptographic Hash (SHA-3 / Keccak family)",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "Based on the Keccak sponge construction, structurally distinct from SHA-2.",
        "usage": "High-assurance hashing with the largest SHA-3 digest.",
    },
    {
        "id": "blake2b",
        "name": "BLAKE2b",
        "category": "Hashing",
        "type": "Cryptographic Hash",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "Optimized for 64-bit platforms; faster than MD5/SHA-1/SHA-2 with strong security.",
        "usage": "Modern general-purpose hashing, checksumming, and keyed hashing (MAC).",
    },
    {
        "id": "blake2s",
        "name": "BLAKE2s",
        "category": "Hashing",
        "type": "Cryptographic Hash",
        "operations": ["Hash"],
        "key": "None",
        "params": [],
        "security": "Recommended",
        "description": "Optimized for 8- to 32-bit platforms, with a 256-bit digest.",
        "usage": "Modern hashing on constrained or embedded systems.",
    },
]

ENCODING_METHODS = [
    {
        "id": "base64",
        "name": "Base64",
        "category": "Encoding",
        "type": "Binary-to-Text Encoding",
        "operations": ["Encode", "Decode"],
        "key": "None",
        "params": [],
        "security": "Not encryption — provides no confidentiality",
        "description": "Represents binary data using 64 printable ASCII characters.",
        "usage": "Embedding binary data in text formats such as JSON, XML, or email.",
    },
    {
        "id": "hex",
        "name": "Hex",
        "category": "Encoding",
        "type": "Binary-to-Text Encoding",
        "operations": ["Encode", "Decode"],
        "key": "None",
        "params": [],
        "security": "Not encryption — provides no confidentiality",
        "description": "Represents each byte as two hexadecimal characters.",
        "usage": "Debugging, displaying keys/hashes, and low-level data inspection.",
    },
    {
        "id": "url",
        "name": "URL Encoding",
        "category": "Encoding",
        "type": "Percent-Encoding",
        "operations": ["Encode", "Decode"],
        "key": "None",
        "params": [],
        "security": "Not encryption — provides no confidentiality",
        "description": "Escapes characters so text can be safely placed in a URL.",
        "usage": "Building query strings and URL path segments safely.",
    },
    {
        "id": "binary",
        "name": "Binary",
        "category": "Encoding",
        "type": "Binary-to-Text Encoding",
        "operations": ["Text to Binary", "Binary to Text"],
        "key": "None",
        "params": [],
        "security": "Not encryption — provides no confidentiality",
        "description": "Represents each byte of text as an 8-bit binary string.",
        "usage": "Teaching how characters are represented at the bit level.",
    },
]

ALL_ALGORITHMS = SYMMETRIC_ENCRYPTION + CLASSICAL_CIPHERS + HASH_ALGORITHMS + ENCODING_METHODS

ALGORITHMS_BY_ID = {algo["id"]: algo for algo in ALL_ALGORITHMS}

STATS = {
    "total_algorithms": len(ALL_ALGORITHMS),
    "encryption_algorithms": len(SYMMETRIC_ENCRYPTION) + len(CLASSICAL_CIPHERS),
    "hash_algorithms": len(HASH_ALGORITHMS),
    "encoding_methods": len(ENCODING_METHODS),
}
